<?php

use Drupal\govuk_integrations_notify_email\EmailMessage;

/**
 * @file
 * Provides basic integration with the GOV.UK Notify (Email) system.
 */


function govuk_integrations_notify_email_send(EmailMessage $email_message) {

  // @TODO Put the client in a service so it's stashed away ready for other requests.

  $client = new GovUKNotify($this->govUkNotifyConfig); // @TODO review

  $response = NULL;
  foreach ($email_message->getRecipients() as $recipient) {
    try {
      $response = $client->sendEmail(
        $recipient,
        $email_message->getTemplate(),
        $email_message->getPersonalisation(),
      );
    }
    catch (ApiException $e) {
      // @TODO Catch or report or something!
    }
  }

  if (!is_null($response)) {
//    $report->setStatus(EmailMessageReportStatus::QUEUED);
//    $report->setMessageId($code);
  }
  else {
//    $report->setStatus(EmailMessageReportStatus::ERROR);
//    $report->setStatusMessage('Sending message failed.');
  }

//  $report->setRecipient($email_message->getRecipients()[0]);

//  $result->addReport($report);

  // @TODO review
  $result = 1;
  return $result;
}
