<?php

/**
 * Get the list of templates from GovUK Notify as select list optinos.
 */
function govuk_integrations_notify_email_get_template_options() {
  $options = [];
  $templates = govuk_integrations_notify_email_get_template_list();
  foreach ($templates as $template) {
    $options[$template['id']] = $template['subject'];
  }

  return $options;
}

/**
 * Get the list of email templates from GovUK Notify.
 *
 * @return array
 */
function govuk_integrations_notify_email_get_template_list() {
  $templates = [];
  $cached_value = \Drupal::cache()->get('govuk_integrations_notify_email_template_list');
  $cached_templates = $cached_value->data ?? [];

  if ($cached_templates) {
    $templates = $cached_templates;
  }
  else {
    $client = new \Drupal\govuk_integrations_notify_email\GovUKEmailClient();
    $result = $client->getTemplateList();
    $templates = $result['templates'] ?? [];
    \Drupal::cache()->set('govuk_integrations_notify_email_template_list', $templates['templates'] ?? [], time() + 60);
  }

  return $templates;
}

/**
 * Get the list of emails we know of, that can be sent via GovUK Notify Email.
 *
 * For now, we store the list in config.
 * Developers can easily add items there, like this:
 *  - module_machine_name_email_ID: 1
 *
 *
 * @return array
 */
function govuk_integrations_notify_email_get_email_list() {
  $emails = \Drupal::config('govuk_integrations_notify_email.emails')->get();

  return $emails;
}
