<?php

/**
 * @file
 * Provides basic integration with the GOV.UK Pay system.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\govuk_integrations_pay\Entity\GovUkPayment;
use Drupal\webform\Entity\Webform;
use Drupal\Core\Routing\TrustedRedirectResponse;
use GuzzleHttp\Psr7\Uri;

/**
 * Implements hook_theme().
 */
function govuk_integrations_pay_webform_theme($existing, $type, $theme, $path) {
  return [
    'govuk_integrations_pay_webform__govuk_confirmation_page' => [
      'variables' => [
        'payment_id' => NULL,
        'payment_amount' => NULL,
        'payment_status' => NULL,
        'payment_message' => NULL,
        'confirmation_message' => NULL,
      ],
    ],
  ];
}


