<?php

/**
 * @file
 * Provides basic integration with the GOV.UK Notify system.
 */

use Drupal\sms\Exception\RecipientRouteException;
use Drupal\sms\Message\SmsMessage;

/**
 * Implements hook_mobile_number_send_sms_callback_alter().
 */
function govuk_integrations_notify_mobile_number_send_sms_callback_alter(&$callback) {
  $callback = 'govuk_integrations_notify_mobile_number_send_sms_callback';
}

/**
 * Custom callback to replace mobile_number_send_sms.
 *
 * @param string $number
 *   Mobile number.
 * @param string $message
 *   Formatted message.
 * @param string $code
 *   Generated code.
 *
 * @return bool
 *   Returned result of SMS send.
 */
function govuk_integrations_notify_mobile_number_send_sms_callback($number, $message, $code = NULL) {
  /** @var \Drupal\sms\Provider\DefaultSmsProvider $sms_provider */
  $sms_provider = \Drupal::service('sms.provider');
  try {
    $sms_message = new SmsMessage(NULL, [$number], $message);

    if (!is_null($code)) {
      $sms_message->setOption('code', $code);
      /** @var \Drupal\sms\Message\SmsMessageResultInterface $result */
    }

    /** @var \Drupal\sms\Message\SmsMessageResultInterface $result */
    $result = $sms_provider->send($sms_message)[0];

    return $result->getResult()->getReport($number)->getStatus();
  }
  catch (RecipientRouteException $e) {
    return FALSE;
  }
}
