govuk_integrations_notify_email.govuk_email_template.*:
  type: config_entity
  label: 'GOVUK Email Template'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    template_id:
      type: string
      label: 'Template ID'
    email_id:
      type: string
      label: 'Email ID'
